---
- name: Deploy Docker Compose application
  hosts: target
  become: true
  tasks:
    - name: Disable CD-ROM repository
      lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb cdrom:'
        line: '# deb cdrom:'
        state: present

    - name: Copy install-docker.sh to target machine
      copy:
        src: /home/dalila/projet-file-rouge/install-docker.sh
        dest: /tmp/install-docker.sh
        mode: '0755'

    - name: Execute install-docker.sh
      shell: /tmp/install-docker.sh

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker Compose directory
      file:
        path: /home/dalila/docker-compose-project
        state: directory
        mode: '0755'

    
    - name: Copy docker-compose.yaml to target directory
      copy:
        src: /home/dalila/projet-file-rouge/docker-compose.yaml
        dest: /home/dalila/docker-compose-project/docker-compose.yaml
        mode: '0755'
     

    - name: Copy Dockerfile to target directory
      copy:
        src: /home/dalila/projet-file-rouge/Dockerfile
        dest: /home/dalila/docker-compose-project/Dockerfile
        mode: '0755'
     
   
    - name: Copy application files to target directory
      copy:
        src: /home/dalila/projet-file-rouge/php/
        dest: /home/dalila/docker-compose-project/php/
        mode: '0755'
       # remote_src: yes
    

   
    - name: Copy SQL file to target directory
      copy:
        src: /home/dalila/projet-file-rouge/stagiaires.sql
        dest: /home/dalila/docker-compose-project/stagiaires.sql
        mode: '0644'


    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: /home/dalila/docker-compose-project
        state: present
        build: true
